### ISSUE TITLE
overall very good work

### ISSUE THREAD

**Issue by Arvrairobo** [Huey-H/LocalHairstylist#1]
i have seen the output of the app, overall very good but it is not as smooth as it should be plus hair styles are really off most of the times, how can it be more accurate? can you please guide me?

**Comment by Huey-H** [comment]
First of all, thank you for your comment. This project was built over a 24 hours period which explains the "smoothness". At this moment, the hairstyles might be a little off due to the distance of the object from the camera. There are still a lot of room for improvement on this project. Due to limitation of time, it was really created as a prototype to backup an idea and to have a rough picture of how it will work. 
The hairstyles are really just images of wigs that I found online which also explains the fluidity of the image. I have implemented the Javascript Face-Detection module and changed some of the code to detect the forehead instead of the nose. Javascript AR can be easy to use but I realize it isn't the most efficient way to do things which also explains the smoothness and accuracy. I would suggest researching on other AR tools if you would like a more precise detection. If you're interested in the JS module, take a look at https://github.com/orls/ccv-purejs . Let me know if you have any other questions, i'll be more than happy to guide/explain it to you.

**Comment by Arvrairobo** [comment]
Thank you very mich for the guidence and i really need it because i am still not sure how to implement it.
All the javascript libraries are not performant as it seems cause they hardly give good FPS rate and also if you in your code all the hair style doesnt stick to the hearld , sometimes it appears and sometimes its not also even if you slightly move the face it disappears so the hairstyle doesnt follow if you move the face or motion it somewhat
How to make it steady that also fits perfectly with distance to camera acuratly that also works with most of faces ?
Any tips or head start or sample code will be greatly appriciated.

**Comment by Arvrairobo** [comment]
I am.on the mobile so please excuse me for typos.

**Comment by Huey-H** [comment]
Sorry for the late reply, I have been caught up with some things lately. I have not had a chance to continue to expand and move on with this side project. Like I said before, this is just a prototype therefore the quality of it. You will have to fit your face to the position that is on the screen to get best results. It is not efficient at all but again, it's just a prototype. You will have to look into better AR face detection libraries that captures multiple points to have it more dynamic. For this project, as long as you fit your head in the position that is printed on the screen, you should be able to see the results.
